dist: xenial

language: node_js

node_js:
  - "8"

stages:
  - lint

git:
  depth: 1

env:
  global:
    - FIND_SH="find $TRAVIS_BUILD_DIR -name '*.sh' -type f -print0"
    - FIND_SLS="find $TRAVIS_BUILD_DIR -name '*.sls' -type f -print0"
    - FIND_JSON="find $TRAVIS_BUILD_DIR -name '*.json' -type f -print0"
    - XARGS="xargs -0 -n1 -I {} -t"

jobs:
  include:
    - stage: lint
      name: EditorConfig Syntax Verification
      install:
        - npm install -g eclint
        - eclint --version
      script:
        - eclint check
    - stage: lint
      name: Shell Script Syntax Verification
      script: eval $FIND_SH | $XARGS shellcheck {} -e SC1088
    - stage: lint
      name: JSON Syntax Verification
      script: eval $FIND_JSON | $XARGS jq --exit-status . {} > /dev/null
    - stage: lint
      name: JSON Lint/Format Verification
      script: eval $FIND_JSON | $XARGS bash -c 'cmp {} <(jq --indent 4 -S . {})'
    #- stage: lint
    #  name: Salt Syntax Verification
    #  install:
    #    - curl -L https://bootstrap.saltstack.com -o bootstrap_salt.sh
    #    - sudo sh bootstrap_salt.sh
    #  script:
    #    - salt-call --local state.sls pwm --state-output=mixed test=True

